"""Python/JavaScript parity gate for bracket selection.

Python (``src/product/selection.py``) is canonical. ``docs/selection.js`` is a
mirror. This asserts the mirror reproduces Python's selected candidate indices
exactly, for every representative objective/preference combination in the
committed fixture.

The fixture is generated by ``scripts/experiments/generate_parity_fixture.py``
from the canonical implementation and committed, so semantic drift shows up as a
reviewable diff rather than only as a red test.

This is a permanent regression gate: any change to selection logic on either side
must be made on both, and the fixture regenerated deliberately.
"""

from __future__ import annotations

import json
import shutil
import subprocess
import tempfile
from pathlib import Path

import pytest

from src.product.selection import (
    candidate_summary,
    constraint_frequency,
    select,
    select_diverse,
    select_with_alternative,
    why_this_differs,
)

REPO = Path(__file__).resolve().parent.parent
ARTIFACT = REPO / "docs" / "data" / "candidates_2026.json"
FIXTURE = REPO / "tests" / "fixtures" / "product" / "parity_2026.json"
JS = REPO / "docs" / "selection.js"

pytestmark = pytest.mark.skipif(not ARTIFACT.exists(), reason="candidate artifact not built")


@pytest.fixture(scope="module")
def artifact():
    return json.loads(ARTIFACT.read_text())


@pytest.fixture(scope="module")
def fixture():
    return json.loads(FIXTURE.read_text())


# ---------------------------------------------------------------------------
# The fixture must match the canonical implementation
# ---------------------------------------------------------------------------


def test_fixture_matches_canonical_python(artifact, fixture):
    """Catches a stale fixture: regenerate rather than editing by hand."""
    tidx = {t["id"]: i for i, t in enumerate(artifact["teams"])}
    for case in fixture["cases"]:
        got = select(
            artifact,
            case["objective"],
            case["preference"],
            team_index=tidx[case["team_id"]] if case["team_id"] else None,
            k=fixture["k"],
        )
        assert got == case["expected_indices"], (
            f"canonical Python no longer reproduces the fixture for "
            f"{case['objective']}/{case['preference']}. If the change is intended, "
            f"regenerate scripts/experiments/generate_parity_fixture.py."
        )


def test_fixture_covers_every_frozen_preference(fixture):
    """A preference with no parity case could drift unnoticed."""
    covered = {c["preference"] for c in fixture["cases"]}
    required = {
        "none",
        "f4_at_least_1_two_three",
        "f4_at_least_2_two_three",
        "f4_mostly_favorites",
        "s16_at_least_1_double_digit",
        "s16_at_least_2_double_digit",
        "s16_no_double_digit",
        "team_reaches_final_four",
    }
    assert required <= covered, f"parity fixture missing {required - covered}"
    assert {c["objective"] for c in fixture["cases"]} == {"ev", "p1"}


# ---------------------------------------------------------------------------
# THE GATE: the JS mirror must reproduce Python exactly
# ---------------------------------------------------------------------------


@pytest.mark.skipif(shutil.which("node") is None, reason="node not available")
def test_javascript_mirror_matches_python(artifact, fixture):
    """Any semantic divergence between the two implementations fails here."""
    runner = """
    const sel = require(process.argv[2]);
    const fs = require('fs');
    const art = JSON.parse(fs.readFileSync(process.argv[3], 'utf8'));
    const fix = JSON.parse(fs.readFileSync(process.argv[4], 'utf8'));
    const tidx = {}; art.teams.forEach((t, i) => tidx[t.id] = i);
    const out = fix.cases.map(c => ({
      objective: c.objective, preference: c.preference,
      indices: sel.selectBrackets(art, c.objective, c.preference,
                                  c.team_id ? tidx[c.team_id] : null, fix.k),
      frequency: sel.constraintFrequency(art, c.preference, c.team_id || ''),
    }));
    console.log(JSON.stringify(out));
    """
    with tempfile.NamedTemporaryFile("w", suffix=".js", delete=False) as f:
        f.write(runner)
        script = f.name

    proc = subprocess.run(
        ["node", script, str(JS), str(ARTIFACT), str(FIXTURE)],
        capture_output=True,
        text=True,
        timeout=180,
    )
    assert proc.returncode == 0, f"node failed: {proc.stderr[:400]}"
    js_out = json.loads(proc.stdout)

    assert len(js_out) == len(fixture["cases"])
    mismatches = []
    for js, case in zip(js_out, fixture["cases"]):
        if js["indices"] != case["expected_indices"]:
            mismatches.append(
                f"  {case['objective']}/{case['preference']}: python={case['expected_indices']} js={js['indices']}"
            )
        if case["frequency"] is not None and js["frequency"] is not None:
            assert abs(js["frequency"] - case["frequency"]) < 1e-9, f"frequency mismatch for {case['preference']}"

    assert not mismatches, (
        "docs/selection.js has diverged from src/product/selection.py. Python is "
        "canonical — fix the mirror, do not regenerate the fixture to match JS.\n" + "\n".join(mismatches)
    )


@pytest.mark.skipif(shutil.which("node") is None, reason="node not available")
def test_javascript_mirrors_select_diverse(artifact, fixture):
    """The Build flow's actual selector must agree across both implementations.

    ``select`` is exercised above via the fixture; this covers the material-
    difference gate, which is what the product calls and which decides whether
    the user sees one bracket or two.
    """
    runner = """
    const sel = require(process.argv[2]);
    const art = JSON.parse(require('fs').readFileSync(process.argv[3], 'utf8'));
    const fix = JSON.parse(require('fs').readFileSync(process.argv[4], 'utf8'));
    console.log(JSON.stringify(fix.diverse_cases.map(
      c => sel.selectDiverse(art, c.objective, c.k))));
    """
    with tempfile.NamedTemporaryFile("w", suffix=".js", delete=False) as f:
        f.write(runner)
        script = f.name

    proc = subprocess.run(
        ["node", script, str(JS), str(ARTIFACT), str(FIXTURE)],
        capture_output=True,
        text=True,
        timeout=180,
    )
    assert proc.returncode == 0, f"node failed: {proc.stderr[:400]}"
    js_out = json.loads(proc.stdout)

    cases = fixture["diverse_cases"]
    assert len(js_out) == len(cases)
    for js, case in zip(js_out, cases):
        py = select_diverse(artifact, case["objective"], k=case["k"])
        assert py == case["expected_indices"], (
            f"canonical Python no longer reproduces the fixture for "
            f"{case['objective']} k={case['k']}; regenerate the fixture deliberately."
        )
        assert js == py, (
            f"selectDiverse diverges for {case['objective']} k={case['k']}: "
            f"python={py} js={js}. Python is canonical — fix the mirror."
        )

    # p1 k=3 returns two brackets on this artifact. If the mirror ever pads a
    # short result to k, this is what catches it.
    short = [c for c in cases if len(c["expected_indices"]) < c["k"]]
    assert short, (
        "no fixture case returns fewer than k; the mirror's short-result "
        "behaviour is no longer covered"
    )


# ---------------------------------------------------------------------------
# Selection semantics
# ---------------------------------------------------------------------------


def test_selection_returns_distinct_champions(artifact):
    """The whole point of hierarchical diversity."""
    for objective in ("ev", "p1"):
        sel = select(artifact, objective, "none", k=3)
        champs = {candidate_summary(artifact, i)["champion_id"] for i in sel}
        assert len(sel) == 3
        assert len(champs) == 3, f"{objective} returned {len(champs)} distinct champions"


def test_objectives_select_different_brackets(artifact):
    """EV and P(1st) are near-orthogonal; identical output would be suspicious."""
    assert select(artifact, "ev", "none", k=3) != select(artifact, "p1", "none", k=3)


def test_selection_is_deterministic(artifact):
    for _ in range(3):
        assert select(artifact, "p1", "s16_at_least_2_double_digit", k=3) == select(
            artifact, "p1", "s16_at_least_2_double_digit", k=3
        )


def test_preference_actually_constrains(artifact):
    """Returned brackets must satisfy the requested preference."""
    for i in select(artifact, "ev", "s16_at_least_2_double_digit", k=3):
        assert artifact["candidates"][i]["dd16"] >= 2
    for i in select(artifact, "ev", "s16_no_double_digit", k=3):
        assert artifact["candidates"][i]["dd16"] == 0


def test_unknown_objective_or_preference_raises(artifact):
    """v1 exposes exactly two objectives; a typo must not silently fall back."""
    with pytest.raises(ValueError, match="unknown objective"):
        select(artifact, "balanced", "none")
    with pytest.raises(ValueError, match="unknown preference"):
        select(artifact, "ev", "contrarian")


# ---------------------------------------------------------------------------
# Frequencies and explanation
# ---------------------------------------------------------------------------


def test_frequencies_come_from_the_full_bank_not_the_candidates(artifact):
    """Counting candidates would bias every user-facing frequency.

    The sampler over-samples unlikely champions on purpose, so the candidate list
    is not a probability sample.
    """
    pref = "s16_at_least_2_double_digit"
    shipped = constraint_frequency(artifact, pref)
    counted = sum(1 for c in artifact["candidates"] if c["dd16"] >= 2) / len(artifact["candidates"])
    assert shipped == artifact["constraint_probabilities"][pref]
    assert abs(shipped - counted) > 1e-6, (
        "candidate-counted frequency coincidentally equals the full-bank value; "
        "this test can no longer detect the substitution"
    )


def test_why_this_differs_describes_a_real_difference(artifact):
    ev_sel = select(artifact, "ev", "none", k=3)
    p1_sel = select(artifact, "p1", "none", k=3)
    reasons = why_this_differs(artifact, p1_sel[0], ev_sel[0])
    assert reasons and all(isinstance(r, str) and r.endswith(".") for r in reasons)
    assert not any("better" in r.lower() or "worse" in r.lower() for r in reasons), (
        "explanations must not claim one bracket is better; the objectives are "
        "near-orthogonal and the honest framing is 'different'"
    )
