"""Generate docs/data/team_factors.json — per-team elo/ap barthag-equivalent ratings.

Feeds Chalk's live probability-base lens in docs/app.js — the only
approach without a precomputed bracket per base (Pool Optimizer,
Exhaustive Search, and Region Beam Search each get a real bracket_2026*
_elo.json/_ap.json generated by scripts/generate_{poolaware,exhaustive,
region}_bracket.py --prob-base elo|ap instead; see BRACKET_FILES /
getRounds() in docs/app.js). Chalk only needs the scalar rating for its
client-side Log5 comparison and same-seed tie-break, so this file is
intentionally minimal.

Superseded 2026-08-15: previously exported roster_adj/coach_adj deltas
(top-5 WARP, coach tournament experience) instead of elo/ap. Replaced
because roster/coach rarely moved any pick for the 2026 field — see
scripts/prob_base_variants.py's module docstring for the investigation.
"""

import json
import sys
from datetime import datetime
from pathlib import Path

PROJECT_ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(PROJECT_ROOT))

from scripts._bracket_export_common import load_team_names
from scripts.mc_pool_backtest import _load_torvik_barthag, load_seeds_and_regions
from src.prediction.ap_probabilities import load_ap_strength_barthag
from src.prediction.elo_probabilities import load_elo_barthag

YEAR = 2026
OUT_PATH = PROJECT_ROOT / "docs" / "data" / "team_factors.json"
DATA_ROOT = PROJECT_ROOT / "data"


def main():
    seeds, regions = load_seeds_and_regions(YEAR)
    if not seeds:
        print(f"ERROR: no seeds found for {YEAR}")
        sys.exit(1)

    barthag = _load_torvik_barthag(YEAR, seeds)
    elo_barthag = load_elo_barthag(YEAR, seeds, DATA_ROOT) or {}
    ap_barthag = load_ap_strength_barthag(YEAR, seeds, seeds.keys(), DATA_ROOT) or {}
    team_names = load_team_names()

    teams = []
    for tid, seed in seeds.items():
        team_barthag = barthag.get(tid, 0.0)
        teams.append(
            {
                "team_id": tid,
                "team_name": team_names.get(tid, tid),
                "seed": seed,
                "region": regions.get(tid, ""),
                "baseline_barthag": round(team_barthag, 4),
                "elo_barthag": round(elo_barthag.get(tid, team_barthag), 4),
                "ap_barthag": round(ap_barthag.get(tid, team_barthag), 4),
            }
        )

    output = {
        "season": YEAR,
        "generated_at": datetime.now().strftime("%Y-%m-%d"),
        "note": (
            "elo and ap_strength are independent rating systems, not Torvik-derived — "
            "selecting one below changes which team Chalk favors in close/same-seed "
            "matchups, not just the displayed percentage. Neither is separately "
            "backtested as a standalone P(1st) strategy; see scripts/prob_base_"
            "variants.py for how much each disagrees with Torvik on the 2026 field."
        ),
        "teams": teams,
    }

    OUT_PATH.parent.mkdir(parents=True, exist_ok=True)
    with open(OUT_PATH, "w") as f:
        json.dump(output, f, indent=2)

    movers = sorted(teams, key=lambda t: abs(t["elo_barthag"] - t["baseline_barthag"]), reverse=True)[:5]
    print("Biggest Torvik-vs-Elo movers:")
    for t in movers:
        print(f"  {t['team_name']:25s} {t['baseline_barthag']:.4f} -> {t['elo_barthag']:.4f}")
    print(f"\nWritten to {OUT_PATH}")


if __name__ == "__main__":
    main()
